name: 'Update Argus Web Player Registry'
description: 'Update the Argus Web Player Registry by providing the game name, URL prefix, and compression setting.'
inputs:
  web-player-repo-pat:
    description: 'Fine-grained personal access token that has write access to the Web Player repo. Example: github_pat_asdf1234'
    required: true
  web-player-env:
    description: 'The environment to update. Example: prod | dev (for prod.json and dev.json respectively)'
    required: true
  game-name:
    description: 'Game name to update. Example: blocksurvivor'
    required: true
  url-prefix:
    description: 'The updated CDN URL prefix. Example: https://cdn.blocksurvivor.com/new1234/WebGL'
    required: true
  compression:
    description: 'Compression setting. Example: brotli | gzip'
    type: string
runs:
  using: 'node20'
  main: 'dist/index.js'
