name: Update Web Player Registry

on:
  workflow_call:
    inputs:
      game_name:
        description: 'Game name to update'
        required: true
        type: string
      url_prefix:
        description: 'URL prefix to update'
        required: true
        type: string
      compression:
        description: 'Compression setting'
        type: string # brotli or gzip, leave empty for no compression

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Call update-web-player-registry.js
      env:
        GAME_NAME: ${{ inputs.game_name }}
        URL_PREFIX: ${{ inputs.url_prefix }}
        COMPRESSION: ${{ inputs.compression }}
      run: node update-web-player-registry.js
